name             'iocdb-infrastructure'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures iocdb-infrastructure'
long_description 'Installs/Configures iocdb-infrastructure'
version          '0.1.0'

depends 'apache2'
depends 'hostnames'
depends 'java'
depends 'elasticsearch'
depends 'python'
depends 'rabbitmq'
depends 'git'
depends 'hadoop'
