#!/bin/sh
#
# /etc/init.d/celery-worker
#
### BEGIN INIT INFO
# Provides:          celery-worker
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage celery workers
# Description:       Manage celery workers
### END INIT INFO

PROC=celery
PROC_DESC="Celery Worker"
USER="iocdb_prov"
START_DIR="/src/iocdb/iocdb"
LOG_FILE="/var/data/log/celery-worker.log"
PID_FILE="/var/data/run/celery-worker.pid"

RETVAL=0
START_COMMAND="celery multi start default -A dispatcher -c 8 -l DEBUG --maxtasksperchild=1 -Q:default celery --logfile=$LOG_FILE --pidfile=$PID_FILE"
STOP_COMMAND="celery multi stop default -A dispatcher -l DEBUG --pidfile=$PID_FILE"

get_pid() {
  if [ -f $PID_FILE ]; then
    PID="`cat $PID_FILE`"
  fi
  if [ "_$PID" != "_" ]; then
    CHILD_PIDS=$(pgrep -P $PID)
  fi
  PID_LIST="$CHILD_PIDS $PID"
}

check_proc_running() {
  IS_RUNNING="false"
  REMAINING=""
  for curr_pid in $PID_LIST; do
    RESULT="`ps -p $curr_pid | grep $curr_pid`"
    if [ "_$RESULT" != "_" ]; then
      IS_RUNNING="true"
      REMAINING="$REMAINING $curr_pid"
    fi
  done
  PID_LIST="$REMAINING"
}

proc_start() {
  get_pid
  check_proc_running

  if [ "_$IS_RUNNING" != "_true" ]; then
     echo "Starting $PROC_DESC..."
     su $USER -c "cd $START_DIR; $START_COMMAND"
     RETVAL=$?
  else
    echo "Process $PID is already running"
  fi
}

proc_stop() {
  get_pid
  check_proc_running

  if [ "_$IS_RUNNING" = "_true" ]; then
    echo "Stopping $PROC_DESC #PID..."
    su $USER -c "cd $START_DIR; $STOP_COMMAND"
    RETVAL=$?

    # Wait up to 10 seconds
    for idx in `seq 1 10`
    do
      sleep 1
      check_proc_running
      if [ "_$IS_RUNNING" != "_true" ]; then
        break
      fi
    done

    check_proc_running
    if [ "_$IS_RUNNING" = "_true" ]; then
      echo "Processes $PID_LIST still running - killing."
      kill -9 $PID_LIST
    fi
  else
    echo "$PROC_DESC is not running"
  fi
}

case "$1" in
  start)
    proc_start
    ;;
  stop)
    proc_stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit $RETVAL
