#!/bin/sh
#
# /etc/init.d/celery-flower
#
### BEGIN INIT INFO
# Provides:          celery-flower
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage celery flower service
# Description:       Manage celery flower service
### END INIT INFO

PROC=celery
PROC_DESC="Celery Flower"
USER="iocdb_prov"
START_DIR="/src/iocdb/iocdb"
LOG_FILE="/var/data/log/celery-flower.log"

RETVAL=0

START_COMMAND="celery -A dispatcher flower --logging=debug --log_file_prefix=$LOG_FILE"

get_pid() {
  PS=`ps aux | grep [c]elery | grep [f]lower1`
  set -- $PS
  pid = $2
}

check_proc_running() {
  IS_RUNNING="false"
  if [ "_$PID" != "_" ]; then
    RESULT="`ps -p $PID | grep $PID`"
    if [ "_$RESULT" != "_" ]; then
      IS_RUNNING="true"
    fi
  fi
}

proc_start() {
  get_pid
  check_proc_running

  if [ "_$IS_RUNNING" != "_true" ]; then
     echo "Starting $PROC_DESC..."
     su $USER -c "cd $START_DIR; $START_COMMAND"
     RETVAL=$?
  else
    echo "Process $PID is already running"
  fi
}

proc_stop() {
  get_pid
  check_proc_running

  if [ "_$IS_RUNNING" = "_true" ]; then
    echo "Stopping $PROC_DESC $PID..."

    kill $PID      

    # Wait up to 10 seconds
    for idx in `seq 1 10`
    do
      sleep 1
      check_proc_running
      if [ "_$IS_RUNNING" != "_true" ]; then
        break
      fi
    done

    for idx in `seq 1 3`
    do
      sleep 1
      check_proc_running
      if [ "_$IS_RUNNING" != "_true" ]; then
        break
      else
        kill -9 $PID      
      fi
    done
  else
    echo "$PROC_DESC is not running"
  fi
}

case "$1" in
  start)
    proc_start
    ;;
  stop)
    proc_stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit $RETVAL
